name: Github Actions Demo

on: 
  push: 
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '15 6 * * 0'


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ":tada: The job was triggered by event: ${{ github.event_name }}"
          echo ":mag_right: The name of your branch is ${{ github.ref }} and your repository is ."
        
      
      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files"
          tree
      
    



